//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Commons/SteeringWheelXBox/SteeringWheelInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Commons/SteeringWheelXBox/SteeringWheelInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @SteeringWheelInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @SteeringWheelInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""SteeringWheelInput"",
    ""maps"": [
        {
            ""name"": ""SteeringWheel"",
            ""id"": ""183b8e9d-988d-415b-8c86-3479c78d6714"",
            ""actions"": [
                {
                    ""name"": ""RotateWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5b14d9e0-a425-4130-94be-ef18dab197f4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""X"",
                    ""type"": ""PassThrough"",
                    ""id"": ""eaaa51b3-89d9-464e-ac7f-2a7ef4cd1e35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fdbff4be-9094-4ec3-b134-5d6e80d32cbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A"",
                    ""type"": ""PassThrough"",
                    ""id"": ""849f83ee-854d-45fa-81ba-e20e40658001"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""PassThrough"",
                    ""id"": ""61d0ad9b-2eb2-40ec-9975-0335434c7a8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""PassThrough"",
                    ""id"": ""31459691-a40a-4f31-89fe-ff2ac1034956"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""PassThrough"",
                    ""id"": ""58f7d61b-21fc-40ab-a3f3-eac60a06dfd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4fd3c7a9-5475-4698-90bf-7519013df461"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""PassThrough"",
                    ""id"": ""999092dd-bac1-4c17-bd85-0cc9542ac5a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WheelLeftTriggerBt"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3cf85671-8fc3-41dd-8332-3231c287e7df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WheelRightTriggerBt"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c4e05df0-9652-4a7b-a2c9-6f3392c8ad56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearShiftUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4549a32b-64f6-4a48-a158-1b6a1fe2e2c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GearShiftDown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8150c16-a4cb-40c7-bcf1-b1886014457e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""21f5700b-2849-4355-b9be-461ad5599df4"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e4513c6-a6a9-44dc-ab95-5229f0d0b961"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a285239a-1cdb-41bf-9b8c-6bf5dac42bff"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8abc49b7-b6d1-4a1d-a14f-b16a18cf98df"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""905d4a27-ffb8-4221-864a-fae1f1e6b06b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78a19a3a-b429-4891-aedb-845ce4041279"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d40cb0bd-cb23-4900-8e7e-c1ab9df38f21"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a63164c-ba50-4bf3-a4b2-da8861d59439"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""126b6043-1cea-4d80-a85d-79c28c9f7d7d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f02b408-7752-48f7-96dc-c29de19c8efc"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearShiftUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a787b9ce-2a10-4efb-88ae-bcab6b6e7bd9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearShiftDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc2a29d6-8ea3-4a86-88d8-e48ab43d87fa"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WheelRightTriggerBt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a91e17d6-5841-4182-bba7-30af7a5b9035"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WheelLeftTriggerBt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SteeringWheel
        m_SteeringWheel = asset.FindActionMap("SteeringWheel", throwIfNotFound: true);
        m_SteeringWheel_RotateWheel = m_SteeringWheel.FindAction("RotateWheel", throwIfNotFound: true);
        m_SteeringWheel_X = m_SteeringWheel.FindAction("X", throwIfNotFound: true);
        m_SteeringWheel_Y = m_SteeringWheel.FindAction("Y", throwIfNotFound: true);
        m_SteeringWheel_A = m_SteeringWheel.FindAction("A", throwIfNotFound: true);
        m_SteeringWheel_B = m_SteeringWheel.FindAction("B", throwIfNotFound: true);
        m_SteeringWheel_Left = m_SteeringWheel.FindAction("Left", throwIfNotFound: true);
        m_SteeringWheel_Up = m_SteeringWheel.FindAction("Up", throwIfNotFound: true);
        m_SteeringWheel_Down = m_SteeringWheel.FindAction("Down", throwIfNotFound: true);
        m_SteeringWheel_Right = m_SteeringWheel.FindAction("Right", throwIfNotFound: true);
        m_SteeringWheel_WheelLeftTriggerBt = m_SteeringWheel.FindAction("WheelLeftTriggerBt", throwIfNotFound: true);
        m_SteeringWheel_WheelRightTriggerBt = m_SteeringWheel.FindAction("WheelRightTriggerBt", throwIfNotFound: true);
        m_SteeringWheel_GearShiftUp = m_SteeringWheel.FindAction("GearShiftUp", throwIfNotFound: true);
        m_SteeringWheel_GearShiftDown = m_SteeringWheel.FindAction("GearShiftDown", throwIfNotFound: true);
    }

    ~@SteeringWheelInput()
    {
        UnityEngine.Debug.Assert(!m_SteeringWheel.enabled, "This will cause a leak and performance issues, SteeringWheelInput.SteeringWheel.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SteeringWheel
    private readonly InputActionMap m_SteeringWheel;
    private List<ISteeringWheelActions> m_SteeringWheelActionsCallbackInterfaces = new List<ISteeringWheelActions>();
    private readonly InputAction m_SteeringWheel_RotateWheel;
    private readonly InputAction m_SteeringWheel_X;
    private readonly InputAction m_SteeringWheel_Y;
    private readonly InputAction m_SteeringWheel_A;
    private readonly InputAction m_SteeringWheel_B;
    private readonly InputAction m_SteeringWheel_Left;
    private readonly InputAction m_SteeringWheel_Up;
    private readonly InputAction m_SteeringWheel_Down;
    private readonly InputAction m_SteeringWheel_Right;
    private readonly InputAction m_SteeringWheel_WheelLeftTriggerBt;
    private readonly InputAction m_SteeringWheel_WheelRightTriggerBt;
    private readonly InputAction m_SteeringWheel_GearShiftUp;
    private readonly InputAction m_SteeringWheel_GearShiftDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "SteeringWheel".
    /// </summary>
    public struct SteeringWheelActions
    {
        private @SteeringWheelInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SteeringWheelActions(@SteeringWheelInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/RotateWheel".
        /// </summary>
        public InputAction @RotateWheel => m_Wrapper.m_SteeringWheel_RotateWheel;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/X".
        /// </summary>
        public InputAction @X => m_Wrapper.m_SteeringWheel_X;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/Y".
        /// </summary>
        public InputAction @Y => m_Wrapper.m_SteeringWheel_Y;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/A".
        /// </summary>
        public InputAction @A => m_Wrapper.m_SteeringWheel_A;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/B".
        /// </summary>
        public InputAction @B => m_Wrapper.m_SteeringWheel_B;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/Left".
        /// </summary>
        public InputAction @Left => m_Wrapper.m_SteeringWheel_Left;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/Up".
        /// </summary>
        public InputAction @Up => m_Wrapper.m_SteeringWheel_Up;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/Down".
        /// </summary>
        public InputAction @Down => m_Wrapper.m_SteeringWheel_Down;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/Right".
        /// </summary>
        public InputAction @Right => m_Wrapper.m_SteeringWheel_Right;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/WheelLeftTriggerBt".
        /// </summary>
        public InputAction @WheelLeftTriggerBt => m_Wrapper.m_SteeringWheel_WheelLeftTriggerBt;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/WheelRightTriggerBt".
        /// </summary>
        public InputAction @WheelRightTriggerBt => m_Wrapper.m_SteeringWheel_WheelRightTriggerBt;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/GearShiftUp".
        /// </summary>
        public InputAction @GearShiftUp => m_Wrapper.m_SteeringWheel_GearShiftUp;
        /// <summary>
        /// Provides access to the underlying input action "SteeringWheel/GearShiftDown".
        /// </summary>
        public InputAction @GearShiftDown => m_Wrapper.m_SteeringWheel_GearShiftDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SteeringWheel; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SteeringWheelActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SteeringWheelActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SteeringWheelActions" />
        public void AddCallbacks(ISteeringWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Add(instance);
            @RotateWheel.started += instance.OnRotateWheel;
            @RotateWheel.performed += instance.OnRotateWheel;
            @RotateWheel.canceled += instance.OnRotateWheel;
            @X.started += instance.OnX;
            @X.performed += instance.OnX;
            @X.canceled += instance.OnX;
            @Y.started += instance.OnY;
            @Y.performed += instance.OnY;
            @Y.canceled += instance.OnY;
            @A.started += instance.OnA;
            @A.performed += instance.OnA;
            @A.canceled += instance.OnA;
            @B.started += instance.OnB;
            @B.performed += instance.OnB;
            @B.canceled += instance.OnB;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @WheelLeftTriggerBt.started += instance.OnWheelLeftTriggerBt;
            @WheelLeftTriggerBt.performed += instance.OnWheelLeftTriggerBt;
            @WheelLeftTriggerBt.canceled += instance.OnWheelLeftTriggerBt;
            @WheelRightTriggerBt.started += instance.OnWheelRightTriggerBt;
            @WheelRightTriggerBt.performed += instance.OnWheelRightTriggerBt;
            @WheelRightTriggerBt.canceled += instance.OnWheelRightTriggerBt;
            @GearShiftUp.started += instance.OnGearShiftUp;
            @GearShiftUp.performed += instance.OnGearShiftUp;
            @GearShiftUp.canceled += instance.OnGearShiftUp;
            @GearShiftDown.started += instance.OnGearShiftDown;
            @GearShiftDown.performed += instance.OnGearShiftDown;
            @GearShiftDown.canceled += instance.OnGearShiftDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SteeringWheelActions" />
        private void UnregisterCallbacks(ISteeringWheelActions instance)
        {
            @RotateWheel.started -= instance.OnRotateWheel;
            @RotateWheel.performed -= instance.OnRotateWheel;
            @RotateWheel.canceled -= instance.OnRotateWheel;
            @X.started -= instance.OnX;
            @X.performed -= instance.OnX;
            @X.canceled -= instance.OnX;
            @Y.started -= instance.OnY;
            @Y.performed -= instance.OnY;
            @Y.canceled -= instance.OnY;
            @A.started -= instance.OnA;
            @A.performed -= instance.OnA;
            @A.canceled -= instance.OnA;
            @B.started -= instance.OnB;
            @B.performed -= instance.OnB;
            @B.canceled -= instance.OnB;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @WheelLeftTriggerBt.started -= instance.OnWheelLeftTriggerBt;
            @WheelLeftTriggerBt.performed -= instance.OnWheelLeftTriggerBt;
            @WheelLeftTriggerBt.canceled -= instance.OnWheelLeftTriggerBt;
            @WheelRightTriggerBt.started -= instance.OnWheelRightTriggerBt;
            @WheelRightTriggerBt.performed -= instance.OnWheelRightTriggerBt;
            @WheelRightTriggerBt.canceled -= instance.OnWheelRightTriggerBt;
            @GearShiftUp.started -= instance.OnGearShiftUp;
            @GearShiftUp.performed -= instance.OnGearShiftUp;
            @GearShiftUp.canceled -= instance.OnGearShiftUp;
            @GearShiftDown.started -= instance.OnGearShiftDown;
            @GearShiftDown.performed -= instance.OnGearShiftDown;
            @GearShiftDown.canceled -= instance.OnGearShiftDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SteeringWheelActions.UnregisterCallbacks(ISteeringWheelActions)" />.
        /// </summary>
        /// <seealso cref="SteeringWheelActions.UnregisterCallbacks(ISteeringWheelActions)" />
        public void RemoveCallbacks(ISteeringWheelActions instance)
        {
            if (m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SteeringWheelActions.AddCallbacks(ISteeringWheelActions)" />
        /// <seealso cref="SteeringWheelActions.RemoveCallbacks(ISteeringWheelActions)" />
        /// <seealso cref="SteeringWheelActions.UnregisterCallbacks(ISteeringWheelActions)" />
        public void SetCallbacks(ISteeringWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_SteeringWheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SteeringWheelActions" /> instance referencing this action map.
    /// </summary>
    public SteeringWheelActions @SteeringWheel => new SteeringWheelActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SteeringWheel" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SteeringWheelActions.AddCallbacks(ISteeringWheelActions)" />
    /// <seealso cref="SteeringWheelActions.RemoveCallbacks(ISteeringWheelActions)" />
    public interface ISteeringWheelActions
    {
        /// <summary>
        /// Method invoked when associated input action "RotateWheel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateWheel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "X" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Y" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnY(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "A" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "B" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnB(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Up" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Down" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WheelLeftTriggerBt" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWheelLeftTriggerBt(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "WheelRightTriggerBt" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnWheelRightTriggerBt(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GearShiftUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGearShiftUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GearShiftDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGearShiftDown(InputAction.CallbackContext context);
    }
}
